server_url: https://headscale-k1fl.onrender.com

listen_addr: 0.0.0.0:8080
metrics_listen_addr: 0.0.0.0:9090

grpc_listen_addr: 0.0.0.0:50443
grpc_allow_insecure: true

private_key_path: /tmp/private.key
noise:
  private_key_path: /tmp/noise_private.key

prefixes:
  v4: 100.64.0.0/10
  allocation: sequential

derp:
  server:
    enabled: false

disable_check_updates: true

ephemeral_node_inactivity_timeout: 30m

database:
  type: postgres
  postgres:
    host: ep-wild-thunder-aqrnakjz-pooler.c-8.us-east-1.aws.neon.tech
    port: 5432
    name: neondb
    user: neondb_owner
    pass: npg_AYhuKTSy3Fr2
    ssl: true
    max_open_conns: 10
    max_idle_conns: 5

dns:
  magic_dns: true
  base_domain: headscale.local

log:
  format: text
  level: info