server_url: http://0.0.0.0:8080
listen_addr: 0.0.0.0:8080
db_type: postgres
db_path: ""

noise:
  private_key_path: /tmp/noise_private.key

prefixes:
  v4: 100.64.0.0/10
  v6: fd7a:115c:a1e0::/48

derp:
  server:
    enabled: false
  urls:
    - https://controlplane.tailscale.com/derpmap/default